const groups=window.GUIDE_DATA||[];
const articles=groups.flatMap(g=>g.items.map(a=>({...a,category:g.category})));
const sideNav=document.querySelector('#side-nav'),view=document.querySelector('#view'),search=document.querySelector('#global-search'),sidebar=document.querySelector('#sidebar');
const catOrder=['Getting started','Village & progression','Dragons & collection','Dragon reference','Leveling & growth','Breeding & hatching','Summons & competition','Battles & activities','Orbs, Gems & items','Events & multiplayer'];
groups.sort((a,b)=>{let x=catOrder.indexOf(a.category),y=catOrder.indexOf(b.category);return (x<0?99:x)-(y<0?99:y)});
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nav(){sideNav.innerHTML=groups.map(g=>`<div class="side-category">${esc(g.category)}</div>${g.items.map(a=>`<a class="side-link" data-id="${esc(a.id)}" href="#article=${encodeURIComponent(a.id)}">${esc(a.title)}</a>`).join('')}`).join('');}
function setActive(id){document.querySelectorAll('.side-link').forEach(a=>a.classList.toggle('active',a.dataset.id===id));}
function home(){document.title='Dragon Village 3 Guide';setActive('');let total=articles.length;const featured=['first-steps','get-dragons','breeding-basics','formation','orbs','fatigue','rapport','draws'].map(id=>articles.find(a=>a.id===id)).filter(Boolean);view.innerHTML=`<div class="page"><p class="breadcrumbs">Guide home</p><h1 class="home-title">Dragon Village 3 Guide</h1><p class="home-intro">A searchable reference for the game's systems, Dragons, activities, and items. Pick a topic or search for a question.</p><div class="info-box"><b>Version note:</b> Core references are based on the 1.0.18 files and research notes. Rotating rates, event schedules, and later changes are linked to official notices or marked for in-game confirmation.</div><div class="search-heading">Browse by game system</div><div class="browse-grid">${groups.map(g=>`<a class="browse-card" href="#category=${encodeURIComponent(g.category)}"><h2>${esc(g.category)}</h2><p>${esc(g.items.slice(0,2).map(x=>x.title).join(' · '))}</p><span class="card-count">${g.items.length} topics</span></a>`).join('')}</div><div class="search-heading">Common questions</div><div class="question-list">${featured.map(card).join('')}</div><div class="source-note">This guide is meant to answer player questions and grow as new game details are added. Open <a href="https://community.withhive.com/dv3/en" target="_blank" rel="noreferrer">official notices</a> for current events and patch changes. ${total} articles are currently indexed.</div></div>`;}
function card(a){return `<a class="question-card" href="#article=${encodeURIComponent(a.id)}">${esc(a.title)}<span>${esc(a.category)}</span></a>`}
function category(name){const g=groups.find(x=>x.category===name);if(!g)return home();document.title=`${name} — Dragon Village 3 Guide`;view.innerHTML=`<div class="page"><p class="breadcrumbs"><button data-home>Guide home</button> / ${esc(name)}</p><h1>${esc(name)}</h1><p class="lead">Browse questions and explanations about ${esc(name.toLowerCase())}.</p><div class="question-list">${g.items.map(card).join('')}</div></div>`;}
function article(id){const a=articles.find(x=>x.id===id);if(!a)return home();document.title=`${a.title} — Dragon Village 3 Guide`;setActive(id);const sections=a.sections.map((s,i)=>`<section id="section-${i}"><h2>${esc(s.title)}</h2>${s.html}</section>`).join('');view.innerHTML=`<div class="page"><p class="breadcrumbs"><button data-home>Guide home</button> / <button data-category="${esc(a.category)}">${esc(a.category)}</button></p><div class="article-layout"><article class="article-body"><h1>${esc(a.title)}</h1><p class="lead">${esc(a.summary)}</p><div class="page-meta"><span class="tag">${esc(a.category)}</span><span>Guide reference ${esc(a.updated||'')}</span></div>${sections}${a.source?`<div class="source-note"><b>Source:</b> ${a.source}</div>`:''}<div class="related"><b>Related topics</b>${articles.filter(x=>x.id!==a.id&&(x.category===a.category||x.tags.some(t=>a.tags.includes(t)))).slice(0,4).map(x=>`<a href="#article=${encodeURIComponent(x.id)}">${esc(x.title)} →</a>`).join('')}</div></article><aside class="toc"><b>ON THIS PAGE</b>${a.sections.map((s,i)=>`<a href="#section-${i}">${esc(s.title)}</a>`).join('')}</aside></div></div>`;}
function results(query){let q=query.trim().toLowerCase();if(!q)return home();let hits=articles.filter(a=>(a.title+' '+a.summary+' '+a.category+' '+a.tags.join(' ')+' '+a.sections.map(s=>s.title+' '+s.html.replace(/<[^>]+>/g,' ')).join(' ')).toLowerCase().includes(q));document.title=`Search: ${query} — Dragon Village 3 Guide`;setActive('');view.innerHTML=`<div class="page"><p class="breadcrumbs"><button data-home>Guide home</button> / Search</p><h1>Search the guide</h1><p class="lead">${hits.length} result${hits.length===1?'':'s'} for “${esc(query)}”</p><div class="question-list">${hits.length?hits.map(card).join(''):'<p>No matching topics. Try a shorter word or browse by system.</p>'}</div></div>`;}
function route(){const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('article=')){article(h.slice(8));return}if(h.startsWith('category=')){category(h.slice(9));return}if(h.startsWith('search=')){let q=h.slice(7);search.value=q;results(q);return}search.value='';home();}
nav();route();window.addEventListener('hashchange',route);
search.addEventListener('input',()=>{let value=search.value.trim();if(value){location.hash='search='+encodeURIComponent(value);results(value)}else{history.replaceState(null,'',location.pathname+location.search);home()}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();search.focus()}if(e.key==='Escape'){search.value='';sidebar.classList.remove('open');document.querySelector('#mobile-menu').setAttribute('aria-expanded','false');home()}});
document.addEventListener('click',e=>{if(e.target.closest('[data-home]')){location.hash='home';home()}const c=e.target.closest('[data-category]');if(c){e.preventDefault();location.hash='category='+encodeURIComponent(c.dataset.category);category(c.dataset.category)}if(e.target.closest('.side-link'))sidebar.classList.remove('open')});
document.querySelector('#mobile-menu').addEventListener('click',e=>{let open=sidebar.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
