window.GUIDE_DATA.push(
{category:"Village & progression",items:[
{id:"village",title:"What can I do in the Village?",summary:"A central place for facilities, Dragons, and progression.",tags:["village","buildings","facilities"],updated:"1.0.18",sections:[{title:"Use the Village as your hub",html:"<p>The Village is where you access facilities and place or manage buildings. Tap a building to see its current function, requirements, and available actions.</p>"},{title:"Prioritize unlocked facilities",html:"<p>Follow the Main Story and the building menus to see what becomes available. The exact unlock level or cost is shown in-game, and can change with updates.</p>"},{title:"Tree of Fruition",html:"<p>After clearing Main Story Chapter 3, place the Tree of Fruition in your Village. It converts Fatigue use into a gauge for Harvest Battles and Rapport Fruit rewards.</p>",source:"<a href='https://community.withhive.com/dv3/en/board/2/4143' target='_blank' rel='noreferrer'>Official Tree of Fruition notice</a>"}]},
{id:"food",title:"How do I grow or collect Dragon Food?",summary:"Food sources and using it to develop Dragons.",tags:["food","farm","seeds","level"],updated:"1.0.18",sections:[{title:"Food sources",html:"<p>Food can come from village activities, quests, battle rewards, and events. The available farm or growing facility shows the seeds, timer, and expected harvest for each crop.</p>"},{title:"Use food on active Dragons",html:"<p>Dragon info shows how much Food is needed for the next level and the stat changes. Consider investing first in Dragons you use for story or other frequent battles.</p>"},{title:"Start growing before a break",html:"<p>If crops have timers, plant the next batch before you stop playing and collect finished crops when you return. Check the item and facility screens for any crop-specific conditions.</p>"}]},
{id:"tamer-level",title:"How do I raise my Tamer Level?",summary:"Account progression and level-gated content.",tags:["tamer","level","unlock","experience"],updated:"1.0.18",sections:[{title:"Gain Tamer progress",html:"<p>Complete Main Story missions and other listed tasks to gain account progress. The Tamer profile or level screen shows your current progress and the next reward or unlock.</p>"},{title:"Find a requirement",html:"<p>If a feature is locked, open its screen and read the prerequisite. The game may require a Tamer Level, story chapter, or another progression condition.</p>"},{title:"Follow the displayed unlock",html:"<p>Use the requirement shown in your current version as the source of truth. Avoid relying on a fixed level from an older guide, since content and unlock rules may be revised.</p>"}]}
]},
{category:"Events & multiplayer",items:[
{id:"events",title:"How do limited-time events work?",summary:"Find event rules, dates, point sources, and reward shops.",tags:["event","limited time","missions","rewards"],updated:"1.0.18",sections:[{title:"Read the event details first",html:"<p>Events may add missions, point goals, rate increases, login rewards, or an exchange shop. Open the in-game event page and note both the closing time and the conditions for earning points.</p>"},{title:"Know which actions count",html:"<p>Do not assume all similar actions count equally. One official Burning Event, for example, awarded Collection points for specified Draws and hatched Dragons, and Fatigue points from Exploration, Dungeons, and Raids. Use the current event's own point table.</p>"},{title:"Spend event currency before it ends",html:"<p>Check the exchange shop's end date and compare the remaining currency with the items you want. Some event shops close at a different time from the event missions.</p>",source:"<a href='https://community.withhive.com/dv3/en/board/2/939' target='_blank' rel='noreferrer'>Official Burning Event guide</a>"}]},
{id:"guild",title:"What are Guilds and Guild Battles?",summary:"Group activities, seasons, and where to check current rules.",tags:["guild","guild battle","season","rank"],updated:"1.0.18",sections:[{title:"Guild features",html:"<p>Guild content is separate from solo story progression. Open the Guild screen to see membership, available activities, schedule, and any current requirements.</p>"},{title:"Guild Battle seasons",html:"<p>Guild Battle seasons and rewards can change. Check the current season screen and official notices for registration, battle windows, score rules, and reward distribution.</p>"},{title:"Prepare your team",html:"<p>Review the mode's battle rules before reusing your story formation. Some updates change saved formations or specific effects across activities.</p>",source:"<a href='https://community.withhive.com/dv3/en/board/13/3291' target='_blank' rel='noreferrer'>Official Raid and Guild Battle season announcement</a>"}]},
{id:"notices",title:"Where can I check current events and updates?",summary:"Use official notices for rotating and time-sensitive information.",tags:["notices","updates","patch","event"],updated:"1.0.18",sections:[{title:"Official notice boards",html:"<p>Use the official WithHIVE community's <b>Notice</b>, <b>Updates</b>, and <b>Events</b> boards for current maintenance, balance, event, and reward information.</p>"},{title:"Check dates and time zones",html:"<p>Most event posts list start and end times in UTC. Convert them to your local time before planning a final attempt or exchange-shop purchase.</p>"},{title:"Use old notices as history",html:"<p>Older notices are useful for understanding a system, but their event dates, featured Dragons, rates, and rewards have expired unless an active notice confirms a rerun.</p>",source:"<a href='https://community.withhive.com/dv3/en' target='_blank' rel='noreferrer'>Official Dragon Village 3 Community</a>"}]},
{id:"bug-help",title:"Where do I report a bug or account problem?",summary:"Find the official support and bug-report routes.",tags:["support","bug","account","help"],updated:"1.0.18",sections:[{title:"Use official support",html:"<p>Open the official community's Support area for Bug Report or Customer Support. Include your device, game version, the screen or mode involved, and the steps that reproduce the issue.</p>"},{title:"For progress or payment issues",html:"<p>Keep relevant transaction receipts and screenshots. Do not post private account credentials or one-time codes in a public forum.</p>"},{title:"Check known issues",html:"<p>Review recent notices before reporting; a current known issue may already have a workaround or follow-up patch.</p>",source:"<a href='https://community.withhive.com/dv3/en' target='_blank' rel='noreferrer'>Official community and support</a>"}]}
]}
);
