window.GUIDE_QUESTIONS = [
  {id:'getting-started',title:'Getting Started',questions:[
    'Is Dragon Village 3 free-to-play friendly?',
    'How does the story compare with PvP for free-to-play players?',
    'What should a new player focus on first?',
    'Which Dragons should a beginner build first?',
    'Which Epic Dragons are especially good for beginners?',
    'Which Dragon would you recommend for each element?',
    'Are well-built Epics better than low-star Legendaries?',
    'Is a 0-star or 1-star Legendary useful?',
    'How do I make a new Dragon stronger?',
    'What matters most: level, rank, stars, Gems, or Orbs?',
    'How far should I level a Dragon before investing elsewhere?',
    'Is level 40 enough, or is level 50 worth the Food cost?',
    'What should a beginner spend Diamonds on?',
    'Which banners should a beginner prioritize?',
    'What should I choose from Selection Cubes and Orb Pickups?',
    'Is it worth using Time Skips early?',
    'Can I catch up after taking a few days off?',
    'Which systems should a new player avoid over-investing in?'
  ]},
  {id:'rank-and-growth',title:'Dragon Rank, Stars, Promotion & Transcendence',questions:[
    'What is the difference between Dragon Rank and Stars?',
    'How do I get a Dragon to 7.0 Rank?',
    'Can Promotion alone reach 7.0?',
    'Roughly how many duplicate Dragons are needed for 7.0?',
    'How rare are high base stats?',
    'What does Promotion do?',
    'What is the difference between a duplicate Dragon and a Promotion Stone?',
    'Can I use a Promotion Stone for Limit Break?',
    'What is Limit Break?',
    'What is Limit Transcendence?',
    'What is the difference between Limit Break and Transcendence?',
    'Do I lose stats if I use an Egg instead of a hatched Dragon?',
    'Is a hatched Dragon better than an Egg for Promotion?',
    'Is an Egg equivalent to a hatched Dragon when upgrading?',
    'Which Dragons should I save Promotion and Rank-Up Stones for?',
    'When is it worth using stones to raise a Legendary?'
  ]},
  {id:'breeding',title:'Breeding & Hatching',questions:[
    'How does Breeding work?',
    'How can I see which Dragons two parents can produce?',
    'Where can I view possible Breeding results?',
    'Where can I view Breeding combinations I have already unlocked?',
    'How are parent elements combined during Breeding?',
    'Why is a Dragon missing from the results despite the parents having the right elements?',
    'What does Breeding Time mean?',
    'Can Breeding Time hint at which Dragon will hatch?',
    'Can Legendary Dragons come from the normal Breeding Lab?',
    'Which Legendary Dragons are normally breedable?',
    'When do I need a Secret Breeding Scroll?',
    'How do I use a Breeding Scroll?',
    'Where do I see a combination after unlocking it with a Scroll?',
    'Why can I not breed Curse Reaper even after using a Scroll?',
    'Can I breed two copies of the same Dragon together?',
    'Why are some Epics repeatable at high odds while some Legendaries are not?',
    'How do Breeding Rate-Up events work?',
    'How does the Breeding event bonus gauge fill?',
    'Do Time Capsules count toward the event gauge?',
    'Should I use Time Capsules during a Limited Breeding event?',
    'How do I choose parents when I want several possible results in one pool?',
    'How do I breed Plumos?',
    'Which Plumos combination can also produce Angel Jr?',
    'How do I breed Power?',
    'How do I breed Curse Reaper?',
    'How do I breed Paruparu?',
    'How do I breed Utriel?',
    'Why do Breeding Times differ between Dragons?'
  ]},
  {id:'orbs',title:'Orbs & Equipment',questions:[
    'What are Orbs?',
    'Are Orbs the moves and attacks a Dragon uses?',
    'How important are Orbs compared with Dragon stats?',
    'What does Orb rarity mean?',
    'What do Orb Stars and duplicates do?',
    'What does +20 mean on an Orb?',
    'Should I upgrade the Orbs I own or wait for higher rarity?',
    'Can an upgraded lower-rarity Orb outperform an unupgraded Legendary Orb?',
    'Which Orbs are good early selector choices?',
    'How should I match an Orb to a Dragon?',
    'Which Orbs work well in Story, PvP, Raids, and World Boss?',
    'Is a specific Pickup Orb worth choosing?',
    'Should I prioritize a Limited Orb if its Dragon may later enter the normal pool?',
    'Can a newer Dragon of the same element use an older Limited Orb?',
    'Can Hope Gems increase a status Orb activation chance?',
    'How do Orb Hit Chance, Power, and Energy Cost work?'
  ]},
  {id:'gems-and-builds',title:'Gems & Builds',questions:[
    'How do Gem Main Stats and Sub Stats work?',
    'Which Sub Stats can appear on each Main Stat?',
    'Can the same stat appear as both Main Stat and Sub Stat?',
    'Which stats are excluded from particular Gem slots?',
    'What happens when I enhance a Gem?',
    'Does enhancing improve an existing Sub Stat or add a new one?',
    'Is the Sub Stat upgrade chosen randomly?',
    'Do Gem Main Stats and Sub Stats have maximum values?',
    'Which Gem Sets are available?',
    'How do Gem Set Bonuses work?',
    'Can identical Set Bonuses stack?',
    'Can Critical Chance bonuses stack?',
    'Which Gem Sets are generally useful?',
    'Which stats should a Physical attacker prioritize?',
    'Which stats should a Magic attacker prioritize?',
    'How important is Speed?',
    'How important are Critical Chance and Critical Damage?',
    'Is Triple Attack a useful Gem stat?',
    'Should I keep Critical Chance on as many Gems as possible?',
    'When is Lifesteal useful?',
    'Why is Lifesteal useful in Raids but less useful in some modes?',
    'Can I recover Gold invested in an enhanced Gem when I sell it?',
    'Is it more efficient to level Dragons or farm better Gems?',
    'What is a good way to farm Gold and Gems?'
  ]},
  {id:'combat-mechanics',title:'Elements, Stats & Combat Mechanics',questions:[
    'How does the Element matchup chart work?',
    'Which elements are strong or weak against Light?',
    'How do the special elements work?',
    'What is the difference between Chaos, Dawn, Divine, Soul, Dream, and Shade?',
    'How much does an Element matchup affect damage?',
    'How does Speed work?',
    'Does Speed only determine turn order, or does it also affect attack and recharge frequency?',
    'How do Critical Hits, Double Attacks, and Triple Attacks work?',
    'How do Status Effects and their activation chances work?',
    'Can Gems or Abilities increase Status Effect chances?',
    'How does Energy work?',
    'When does Energy regenerate?',
    'What happens to Energy when I swap Dragons?',
    'How do on-entry Abilities such as Roar work?',
    'Can I stack an entry Ability by repeatedly swapping a Dragon in and out?',
    'Can I swap immediately, or must I attack first?'
  ]},
  {id:'gacha-and-diamonds',title:'Draws, Tickets, Pity & Diamonds',questions:[
    'How does Pity work?',
    'Does Pity carry over between banners or reset?',
    'Does Pity behave the same for every ticket type?',
    'Do Special Pickup Tickets carry into the next rotation?',
    'Should I use tickets immediately or save them?',
    'Should I save Uncommon and Blue Tickets for future Dragons?',
    'When do Limited and Pickup Dragons enter the normal pool?',
    'Do Limited Orbs also enter the normal pool?',
    'Which banners offer good value?',
    'Which banners should beginners skip?',
    'How many Diamonds should I save for a specific Dragon?',
    'Should I spend Diamonds on Draws, Breeding Speedups, Stamina, or Events?',
    'What is the best general use for Diamonds?',
    'What should I buy in the Draw Shop?',
    'Are Orb banners often better value than Dragon banners?',
    'Is one copy of a Legendary worth the cost?',
    'When is a 0-star or 1-star Legendary worth investing in?'
  ]},
  {id:'guilds',title:'Guilds & Guild War',questions:[
    'Is joining a Guild worthwhile?',
    'What benefits does a Guild provide?',
    'Are there Guild-exclusive Orbs?',
    'Should I join any available Guild or look for a particular one?',
    'How do I find a good and active Guild?',
    'When should I move to a stronger Guild?',
    'How does Guild War work?',
    'What happens when a Dragon is defeated in Guild War?',
    'Can I use that Dragon in another attempt?',
    'How many built Dragons should I prepare for Guild War?'
  ]},
  {id:'raids',title:'Raids',questions:[
    'How does Raid Score work?',
    'Why does the boss HP bar lock during my attack?',
    'Why is my damage or score capped?',
    'Why are there two attempts?',
    'Which of my two attempts counts?',
    'How does Raid ranking work?',
    'What rewards does the Raid host receive?',
    'Does the host count normally in the ranking?',
    'Does the host automatically get maximum or double rewards?',
    'How do first-place rewards work?',
    'What is the chance of getting Raid Eggs?',
    'Does my placement affect the Raid Egg chance?',
    'Which Dragons are strong against each Raid boss?',
    'Why does Haze deal so much damage to Lichmond?',
    'How should a Raid build differ from a normal PvE build?',
    'Which Raid boss Abilities have special mechanics?',
    'How can Tellus affect or disable Maldek?',
    'How does Maldek Flight work, and how can I remove it?'
  ]},
  {id:'trading-and-codify',title:'Trading, Codify & Raid Eggs',questions:[
    'Is there trading in Dragon Village 3?',
    'Which Eggs can be traded?',
    'Can normal Dragon Eggs be traded?',
    'Can only Raid Eggs be codified?',
    'What does Codify mean?',
    'How do I create an Egg Code?',
    'How does another player redeem an Egg Code?',
    'Can Magnas be codified, or only Raid Dragons?',
    'Can Raid Eggs be traded across servers?',
    'What happens to the original Egg after it is codified?'
  ]},
  {id:'story-troubleshooting',title:'Story & Difficult Stages',questions:[
    'How do I beat Dragon Slayer?',
    'How does the Magnello and Hyeonmu swap strategy work?',
    'Why weaken Dragon Slayer by lowering its Attack by six stages first?',
    'How do I beat Illuid in Story 7-7?',
    'Which Lightning or Chaos Dragons work against Illuid?',
    'What strategy works for Story 7-15?',
    'What strategy works for Story 8-15?',
    'Which teams work well for Story 8-15?',
    'How do I counter Cozy in the final Story 2v2?',
    'How do I counter Cozy on Underground Castle Level 10?',
    'How do I counter Poison River?',
    'How do I counter Angel Jr?',
    'How far below an enemy level can my team be and still win?',
    'Do Story enemies have hidden stats compared with normal Dragons?'
  ]},
  {id:'world-boss',title:'World Boss',questions:[
    'Do all ten Dragons need to be highly leveled for World Boss?',
    'Is it better to level more Dragons moderately and maximize their Gems?',
    'Which stats increase World Boss damage the most?',
    'How important is Speed in World Boss?',
    'Which Gem Sets are best for World Boss?',
    'Do Gem Set Bonuses work in World Boss?',
    'Do damage Set Bonuses such as Physical Damage +10% work there?'
  ]},
  {id:'fruit-tree-rapport-fatigue',title:'Tree of Fruition, Rapport & Fatigue',questions:[
    'How does the Tree of Fruition work?',
    'How do I maximize my Fruit Tree score?',
    'Is stacking Attack and Magic enough for a high Fruit Tree score?',
    'Which Dragons are good for the Tree of Fruition?',
    'How does Rapport work?',
    'What do Rapport Fruits do?',
    'Why does the tutorial make me bond with Haze?',
    'Does the tutorial consume a valuable resource, or is it returned?',
    'Where should I spend Fatigue during Burning events?',
    'Is Gathering or Dungeon more efficient for Fatigue?',
    'Are Fatigue Potions worth buying or using?'
  ]},
  {id:'stickers',title:'Stickers',questions:[
    'How does the Sticker system work?',
    'Where do Sticker Packs come from?',
    'Can Sticker Packs contain duplicates?',
    'Can Gold Stickers also be duplicates?',
    'How does Sticker Request work?',
    'Is Sticker Request a trade?',
    'Why might another player reject a Sticker Request?',
    'Can players trade Stickers directly?'
  ]},
  {id:'other-systems',title:'Other Systems & Resources',questions:[
    'Is Gathering the only way to get Evolution Materials?',
    'Where is the most efficient place to farm a particular rare material?',
    'When should I spend Fatigue on Gathering instead of Dungeon?',
    'Are Food upgrades or the 10k Food Harvest worthwhile?',
    'How do Habitat upgrades using Gems work?',
    'Do Habitat Gem upgrades take time?',
    'Why upgrade Habitats with Gems?',
    'What should I do with a special-element Dragon if I have not unlocked its Temple?',
    'Can I keep that Dragon in the Sanctuary temporarily?',
    'What does the extra Breeder from the Ad Pass provide?'
  ]},
  {id:'current-info',title:'Current Info & Rotating Events',changing:true,questions:[
    'Which Coupon Codes work right now?',
    'Where can I find current Coupon Codes?',
    'Do Coupon Codes expire?',
    'Which banner is currently active?',
    'When is the next banner?',
    'Which Dragon is currently in Limited Breeding?',
    'Which Breeding Rate-Up events are active now?',
    'Which Dragons or Orbs are coming in the next patch?',
    'Is this specific event worth participating in?',
    'Should I open one or ten Event Chests at a time?',
    'Which Event Ranking tier should a free-to-play player target?',
    'What does the newest Dragon Chroma look like?'
  ]}
];
