/* Practical walkthroughs, distinct from the static game-data catalog. */
window.GUIDE_DATA.push({category:"Walkthroughs & strategy",items:[
{id:"new-tamer-route",title:"New Tamer route: what should I do first?",summary:"A step-by-step routine for unlocking systems and building a useful first team.",tags:["beginner","new player","story","missions","team"],updated:"1.0.18",sections:[
{title:"1. Follow the Main Story",html:"<p>Use the Main Story as your unlock path. It introduces Exploration and opens more systems as you clear chapters. When you hit a gate, read the requirement on the stage or feature screen; the game may require a specific story clear, Tamer level, or mission claim.</p>"},
{title:"2. Clear Missions and Triumph",html:"<p>Claim completed Main Story, Missions, and Triumph rewards. They are separate lists, and some Triumph objectives ask for a manual interaction. If you feel stuck, check each list and use its <b>Move</b> button where available.</p>"},
{title:"3. Build a balanced core team",html:"<p>Raise a small team you actually use instead of spreading scarce growth items across every Dragon. Cover more than one element and damage type, and keep a durable Dragon available for fights that punish a fragile lineup. Open <a href="#dragons">the Dragon index</a> to compare base stats, abilities, and moves.</p>"},
{title:"4. Keep long timers running",html:"<p>Start food, breeding, hatching, and building timers before you log off. Collect finished crops and eggs to free their slots, and spend Fatigue on a stage that advances a mission or supplies a material you need.</p>"},
{title:"5. Unlock the Tree of Fruition",html:"<p>The official Rapport notice says the Tree of Fruition opens after clearing <b>Chapter 3, Episode 10</b>. Rapport gifts provide another progression path; check the in-game Tree screen for each Dragon's current requests and rewards.</p>",source:"<a href='https://community.withhive.com/dv3/en/board/2/4143' target='_blank' rel='noreferrer'>Official Tree of Fruition and Rapport notice</a>"}
]},
{id:"which-dragons-to-draw",title:"Which Dragons should I draw for?",summary:"Pick a banner and a team role deliberately; use dated tier lists only as a snapshot.",tags:["draw","summon","banner","beginner","recommendation","team"],updated:"2026-09",sections:[
{title:"Start with the banner details",html:"<p>Before spending, open the banner information and check its featured Dragons, rates, draw currency, guarantee or exchange rules, and end date. A Dragon recommendation is useful only if that Dragon is in the pool you can currently access and you can reach the banner's guarantee.</p>"},
{title:"Choose for a job your team needs",html:"<p>Look for a clear gap: a reliable damage dealer, a Dragon with useful control or support, or a second element for stages where your current team is disadvantaged. Compare the candidate's <b>ability and both moves</b> in the <a href="#dragons">Dragon catalog</a>; the highest rarity by itself does not tell you whether it fits your team.</p><p>If you are early in the story, keep resources for a banner you can finish and build the Dragons you already have. Avoid spending across several banners when you cannot meet their exchange or guarantee threshold.</p>"},
{title:"A dated community shortlist",html:"<p>A community tier list published September 18, 2026 and marked for version 1.0.16 highlights <b>Power Dragon, Florea, and Dragon Slayer</b> among high-ranked picks. Treat those names as a dated shortlist, not a current 1.0.18 ranking or a promise that they are available on today's banner. Recheck the live pool and patch notes before using it.</p>",source:"<a href='https://www.pocketgamer.com/dragon-village-3/tier-list/' target='_blank' rel='noreferrer'>Pocket Gamer Dragon Village 3 tier list, version 1.0.16 snapshot</a>"},
{title:"Use the index to compare",html:"<p>Filter the catalog by element, rarity, ability, or move. Use the obtain field to see whether a Dragon has a listed route beyond Draw. Availability and pickup status can change, so confirm them on the in-game screen.</p>"}
]},
{id:"raid-score-guide",title:"How do I get a good Raid score?",summary:"Prepare a repeatable team and spend both attempts on your strongest realistic result.",tags:["raid","score","boss","damage","team"],updated:"2026-09",sections:[
{title:"Learn the boss before spending attempts",html:"<p>Read the Raid boss hint and watch its skill or phase changes. Build around the boss's mechanics: bring the right resistance or status answers, avoid a move that feeds its counter, and preserve enough durability to keep dealing damage.</p>"},
{title:"Plan a damage sequence",html:"<p>Use a manual run to learn the turn order, then arrange buffs, defense or resistance reduction, and high-value attacks so your best damage lands while the boss is vulnerable. Check Orb skill costs and effects in the <a href="#orbs">Orb catalog</a>. If a status effect is part of your plan, confirm it can affect that boss.</p>"},
{title:"Use both daily attempts",html:"<p>The September 2026 Raid rules allow <b>two attempts</b>. The higher score is normally counted; when both results are 2,000 or below, they are added together up to 2,000. Each individual score is capped at 20% of that Raid boss's maximum HP. The notice says combined contribution above 10,000 counts as a success if the Raid times out. Host and top contributor receive double rewards under those rules.</p><p>These are live season rules and can change. Check the current Raid screen and notice before planning around the threshold.</p>",source:"<a href='https://community.withhive.com/dv3/en/board/2/3649' target='_blank' rel='noreferrer'>Official Raid contribution rules notice, September 2026</a>"},
{title:"Coordinate with the guild",html:"<p>Share the boss mechanic and a practical damage target with your guild. If you host, keep the Raid open long enough for members to join and use their attempts. Track contribution in the current Raid screen because displayed rewards and season rules can differ.</p>",source:"<a href='https://community.withhive.com/dv3/en/board/13/3291' target='_blank' rel='noreferrer'>Official Raid season notice</a>"}
]},
{id:"clear-hard-stage",title:"How do I clear a difficult stage?",summary:"Read the stage table, adjust the team, then change one thing at a time.",tags:["stage","expedition","dungeon","walkthrough","boss","team"],updated:"1.0.18",sections:[
{title:"Look up the encounter",html:"<p>Open <a href="#stages">the Stage Index</a> and search the zone or stage. It lists the 1.0.18 recommended power, Fatigue cost, and known enemy levels. Recommended power is a guide value from the game table, not a guarantee of victory.</p>"},
{title:"Check your matchup",html:"<p>Compare your team's elements with the enemy's. Swap in a Dragon with a better matchup, and check whether the enemy relies on physical attacks, magic, or a status effect. Read each ability and move before spending growth materials.</p>"},
{title:"Fix the failing part",html:"<ul><li><b>You lose a Dragon early:</b> put a sturdier Dragon in front or add a defensive/support skill.</li><li><b>The timer runs out:</b> replace a low-damage slot and use buffs or defense reduction before burst skills.</li><li><b>A status effect stops your turn:</b> bring resistance or a move that removes or prevents that status, if available.</li><li><b>You barely miss:</b> improve the team's core levels or Orbs and retry before spending broadly on the whole roster.</li></ul>"},
{title:"Use manual battle to learn",html:"<p>Turn off Auto for a try. Watch target order and skill timing, then change one formation slot, Orb, or move for the next attempt. After a stage is stable, use Auto or repeat battle for farming if the mode allows it.</p>"}
]},
{id:"get-a-dragon",title:"How do I get a specific Dragon?",summary:"Read its catalog entry, then check the current in-game route.",tags:["obtain","collection","dragon","breeding","draw","shop"],updated:"1.0.18",sections:[
{title:"Start with the Dragon entry",html:"<p>Search the <a href="#dragons">Dragon index</a> by name, element, or ability. The entry includes the 1.0.18 reference obtain label where it was present in the local table and whether a breeding timer is listed.</p>"},
{title:"Follow the matching route",html:"<p><b>Draw:</b> check the live banner's pool, rates, and guarantee. <b>Breeding:</b> check parent requirements, timer, and egg details in the game. <b>Shop or guild:</b> confirm stock and currency on that shop screen. <b>Event or progression:</b> read the event or reward condition and its expiry. The local catalog records routes from version 1.0.18 and cannot show your current rotating banner.</p>"},
{title:"Check for a direct reward first",html:"<p>Before spending Diamonds, check story, Triumph, event, and guild rewards. Some Dragons or eggs can be earned through progression or a shop route. Compare the in-game cost and time with the route shown in the catalog.</p>"}
]},
{id:"farm-growth-materials",title:"Where should I farm growth materials?",summary:"Use each mode's reward preview and target only the material you need.",tags:["farm","materials","growth","gold","food","dungeon"],updated:"1.0.18",sections:[
{title:"Read the reward preview",html:"<p>Check the stage or Dungeon reward panel before spending Fatigue. The <a href="#stages">Stage Index</a> identifies encounters and recommended power, while the in-game preview is the best check for current drops and account-specific unlocks.</p>"},
{title:"Farm the shortest reliable route",html:"<p>Choose a stage you can clear consistently that shows the item you need. Higher stages may offer more rewards but can cost more Fatigue or fail more often. Include event missions and first-clear rewards in your decision.</p>"},
{title:"Gold, food, and Dragon growth",html:"<p>Collect village production and mission rewards regularly. Start food growth when its slot is free, and use battle modes whose preview lists the required material. Avoid upgrading every Dragon at once; concentrate on your active team until a new encounter asks for a different element or role.</p>"}
]},
{id:"read-dragon-catalog",title:"How to read the Dragon catalog",summary:"Understand the catalog fields and compare Dragons before investing.",tags:["dragon","reference","stats","ability","moves","elements"],updated:"1.0.18",sections:[
{title:"Stats and rarity",html:"<p>Catalog stats are the 1.0.18 table reference values. Your Dragon's displayed stats change with level, growth, equipment, and other bonuses. Rarity describes the game's classification; compare the actual role and skills before deciding where to invest.</p>"},
{title:"Ability and moves",html:"<p>Abilities are passive or conditional effects. A Dragon's basic move and ultimate move show their type, element, power, accuracy, and energy cost when those values exist in the data. Descriptions can reveal healing, control, stat changes, or team effects that raw power misses.</p>"},
{title:"Obtain and timers",html:"<p>Breeding and hatch timers and obtain labels come from the 1.0.18 tables. A listed Draw or Shop route is not proof that the route is available today; use the game screen for current banners and stock.</p>"}
]}
]});
